### ISSUE TITLE
binary release

### ISSUE THREAD

**Issue by siddharthist** [mheese/journalbeat#19] opened 2016-06-14 09:58 UTC
To make journalbeat easier to package, it would be awesome if there were pre-compiled binaries that could be downloaded.

For an example Makefile, see [CiscoCloud/mesos-consul's Makefile](https://github.com/CiscoCloud/mesos-consul/blob/master/Makefile).

**Comment by gmarkey** [comment] 2016-06-14 10:04
If it helps, I should have an RPM spec for this; have reminded myself to check tomorrow morning.

**Comment by siddharthist** [comment] 2016-06-14 10:08
An RPM spec would be nice, but we'd also like to create our own custom package (so a binary release is still necessary).

**Comment by nicorevin** [comment] 2016-06-15 11:44
There can be a problem with systemd dependency. I build it on Debian with systemd 215 and run on CoreOS with systemd 225. Haven't seen any problems so far but still it should be kept in mind.

**Comment by mheese** [comment] 2016-06-15 15:40
Yes, the version and distribution specifics of journald have prevented me so far from doing a binary release. However, it is encouraging to here what @nicorevin is writing. Maybe the problem is less complicated than I anticipated.

Still, one should keep in mind that systemd can be compiled with a lot of different options and that adds different library requirements to it, and they will ultimately be reflected in the journal build.

We should aim for the following platforms IMO:
- CoreOS - simply because this is where I want to run it 😄 
- Red Hat / Fedora (can probably be accomplished with the same spec file)
- Debian / Ubuntu (I'm not experienced with that)
- Gentoo (as it is easy)
- Arch Linux

any other package suggestions?

Apart from that, maybe we'll also aim for a "universal" binary, I've got an idea on how to approach that.

**Comment by siddharthist** [comment] 2016-06-20 10:24
@mheese One option for releases is building the binaries using Travis CI + different Dockerfiles. I have a CentOS Dockerfile set up here, and I'd be happy to make a PR to incorporate that kind of CI build here.

**Comment by mheese** [comment] 2016-06-20 15:49
@siddharthist that's a very good start ... don't hold back on a PR :)

**Comment by siddharthist** [comment] 2016-06-20 17:12
Okay, I'm working on getting a working Travis build.

**Comment by nicorevin** [comment] 2016-07-27 20:53
merged #29, but it turns out only @mheese can enable the hook to activate Travis builds.

**Comment by siddharthist** [comment] 2016-07-28 08:03
@nicorevin If that's the case, I don't think this issue should be closed. The next release of journalbeat still won't be automatically compiled and released.

**Comment by nicorevin** [comment] 2016-07-28 14:48
https://travis-ci.org/nicorevin/journalbeat/jobs/148000771
What am I doing wrong? @siddharthist @pgaubatz

**Comment by mheese** [comment] 2016-07-28 15:21
@siddharthist, @nicorevin I activated travis and added the build badge to the README. Sorry for dropping the ball on this.

**Comment by pgaubatz** [comment] 2016-07-28 15:22
Hey @nicorevin!

You basically have to update `api_key` in `.travis.yml`.
This can be done be installing the travis CLI (i.e., using `gem install travis`) and running `travis setup releases --force` in the project directory.

**Comment by nicorevin** [comment] 2016-07-28 16:14
I think it will be better if @mheese gets it updated for this repo.

**Comment by mheese** [comment] 2016-07-29 01:09
yup, I will do that tonight!

**Comment by siddharthist** [comment] 2016-07-29 08:05
Great, thanks to both of you for your continued work!

**Comment by mheese** [comment] 2016-07-30 07:03
phew ... after struggling with the travis CLI a bit, it is **finally** working!

I tagged a first release and it builds correctly and is publishing release binaries. Thanks again to everybody involved here: @siddharthist @pgaubatz @nicorevin !

**Closed by mheese** 2016-07-30 07:03 UTC

**Comment by siddharthist** [comment] 2016-07-30 09:49
Thank you @mheese!
