### ISSUE TITLE
Log sequence issue with millisecond Timestamp in ES 

### ISSUE THREAD

**Issue by johnmarcou** [mheese/journalbeat#66] opened 2017-05-16 05:26 UTC
Hi all,

I am using journalbeat in a Docker container on our CoreOS systems to push the logs to ELK.
Dockerd is set with the journald logging driver in order to push the container logs to journald as well.

The issue I am experiencing is the logs lose the sequence order when both logs occur during the same millisecond, since Elastic (and libBeat) doesn't support microsecond resolution timestamps.
This make the logs, multiline logs, and tracelog, unreadable.

Then, to make sure the doc/event sequence will be preserved, I modified the code to push @timestamp field to ELK based on "Now" with no collision on millisecond timestamp, instead of the REALTIME_TIMESTAMP.

This is the trick in `beater/journalbeat.go`:
```golang
//event["@timestamp"] = common.Time(time.Unix(0, int64(rawEvent.RealtimeTimestamp)*1000))
event["@timestamp"] = common.Time(time.Now())
time.Sleep(1 * time.Millisecond)
```

Ok, it's not the best idea of the year, because:
 - we are loosing the __REALTIME_TIMESTAMP from journald or the _SOURCE_TIMESTAMP from the logger process
 - this inject latency in logs buffer construction, but should not delay the shipping as much
 - this create bad timestamp if journalbeat is restarting in head mode
 - it's ok during following mode though

but this is the only way I found to cope with ELK millisecond timestamp limitation to keep the logs in order.

If someone has a better idea or usage ... ?

**Comment by mheese** [comment] 2017-05-16 23:53
Hm, that's really a bummer. Let me think about this for a couple of days please. Right now I tend to agree. It looks like the only viable solution.

**Comment by nicorevin** [comment] 2017-05-17 11:01
I recall this https://github.com/mheese/journalbeat/pull/30
We could probably add this back as an option. But `time.Now()` can be more of a PITA for those who expect more or less accurate timestamps.

I would rather seek a proper fix for this...

Let's start unwrapping things.
1. We get @timestamp field containing milliseconds before passing the message to the output.
2. `__REALTIME_TIMESTAMP` which is `in microseconds since the epoch UTC, formatted as a decimal string` is converted [here](https://github.com/mheese/journalbeat/blob/f2b222ab48f187fc6d09f8d3edcea3aa98de848f/beater/journalbeat.go#L157).
3. We are relying on [`common.Time`](https://github.com/elastic/beats/blob/8bec23294d5482d7e3a612d7c56abd522f3474c7/libbeat/common/datetime.go#L13) where our microseconds are cut off. I would expect this to be [`time.RFC3339Nano`](https://golang.org/pkg/time/#pkg-constants)
4. Following [the elastic docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html#custom-date-formats) the root cause is [here](http://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormat.html) - see more in [this discussion](https://discuss.elastic.co/t/elk-truncates-microseconds-nanoseconds-precision-from-rfc-3339-timestamps/43619) and corresponding github issues.

As a workaround (until elasticsearch will have got rid of this joda legacy) we could pass `__REALTIME_TIMESTAMP` as is as an int and sort logs based on this field.

**Comment by johnmarcou** [comment] 2017-05-17 12:42
Thank you for your reply.

For your information, I am finally use this solution:
```golang
		// TODO: type and input_type should be derived from the system journal
		event["type"] = jb.config.DefaultType
		event["input_type"] = jb.config.DefaultType
    event["@real_timestamp"] = common.Time(time.Unix(0, int64(rawEvent.RealtimeTimestamp)*1000))
    event["@timestamp"] = common.Time(time.Now())
    time.Sleep(1 * time.Millisecond)
```

The index time series is based on @timestamp, but I display the @real_timestamp. Both are Date type in ES. My understanding is ES can store/keep microsecond, but can't sort on it.

With elktail, I sort on @timestamp, but display the @real_timestamp, where I can see the microsecond.

Same with logtrail, I sort on @timestamp, but the display time @real_timestamp.

The little issue is when we reparse the journal in head mode, the old record appear as when they have been actually pushed to ES, but I can live with that ...

**Comment by nicorevin** [comment] 2017-05-17 13:27
@johnmarcou I think any log source will face the same issues working with ES since it is the problem in ES way of dealing with dates.
In ES you can ask to sort like `{"_source":["*"],"size":10,"sort":[{"your_integer_field":{"order":"desc"}}],"query":{"filtered":{"filter":{"term":{"beat.name": "journalbeat"}}}}}'`

I don't think switching to `time.Now()` helps anyhow though. When your logs appear within the same millisecond how is their sequence preserved in this case?

**Comment by johnmarcou** [comment] 2017-05-17 22:02
Because of the ```time.Sleep(1 * time.Millisecond)```.

This 6 logs in 2 milliseconds ```|ABC|DEF|``` becomes 6 docs pushed in 6 milliseconds```|A|B|C|D|E|F|```.

**Comment by mheese** [comment] 2017-05-19 00:10
ok, so when I follow the discussions that @nicorevin posted correctly, ES has some baggage why this won't work how we want it with real timestamp. If we keep the real timestamp still around like @johnmarcou suggests above, and make that `time.Now()` behaviour optional (config file), then I think we can serve all parties:
- people who want to have real timestamp as `@timestamp` can still do it - as it still should be the default behaviour imho
- people who want to have sorting capabilities, can let the system generate new timestamps, but they also won't lose the real timestamp

@nicorevin @johnmarcou what do you guys think?

**Comment by nicorevin** [comment] 2017-05-19 10:42
`time.Sleep`ing for a `ms` is a nice hack but I would rather rely on UNIX timestamps for sorting. Otherwise we will create one more potential bottleneck that people would check in case of logs falling behind.
For example our setup allows to log up to 240K messages per second per systemd unit per host. So it depends on our ELK setup how fast we will ingest these volumes.
If we apply `time.Sleep` we will simply lose this throughput.
We are not passing `__REALTIME_TIMESTAMP` to the ELK. But we pass `__SOURCE_REALTIME_TIMESTAMP`. Sorting based on `__SOURCE_REALTIME_TIMESTAMP` seems to me pretty reasonable in this case.

**Comment by johnmarcou** [comment] 2017-05-22 03:31
I finally try the @nicorevin suggestion, by doing this:
```golang
event["@timestamp"] = common.Time(time.Unix(0, int64(rawEvent.RealtimeTimestamp)*1000))
event["@unix_timestamp"] = int64(rawEvent.RealtimeTimestamp)
```

The @timestamp field is a Date format, convert by the libbeats functions.
The @unix_timestamp is the RealTime from journad in Int64 without conversion, to keep the millisecond.

On Logtrail plugin, I use the @unix_timestamp as timestamp to sort, and @timestamp as timestamp to display. Works like a charm so far.

Rem: I am not using ```source_realtime_timestamp``` or ```source_monotonic_timestamp``` since these fields are not always present, depends on the logger process. For example, docker (with the journald logging driver) doesn't append these fields every time. But it's appear ```real_timestamp``` is always here, and is the journald timestamp.

Finally, I suggest you guys to add this @unix_timestamp (line 2) to allow journalbeat users to have :
 - @timestamp: which respect the Elastic requirement, as a Date, but lose millisecond
 - @unix_timestamp: which provides a way to sort and keep sequence order, as a Int

**Closed** 2017-06-05 14:40 UTC
Labels: bug
